翻译完成，原文译文对照版
npc-network/translator-website pull request #13
Opened 2018-07-01 15:37 UTC by blakegao

翻译完成，原文译文对照版

2018-07-03 12:44 UTC, XiaohuaNpc commented on source/_drafts/not-as-many-as-you-think.md
> +当时很容易丢币。 它们的价值不高，所以人们没有花时间保证它们的安全行并支持它们。
back them up   备份他们

2018-07-03 12:56 UTC, XiaohuaNpc commented on source/_drafts/not-as-many-as-you-think.md
> +不能忽视的是，40 BTC价值几十万美元，以及500万美元有保障，流动投资足以提供一个非常舒适的退休生活。
有保障有流动性的投资 （保障后面的逗号，感觉断句会有点奇怪。）

2018-07-03 12:57 UTC, XiaohuaNpc requested changes
well done.  ^_^
提了两个小建议，你看一下

2018-07-03 15:17 UTC, blakegao commented
感谢建议，已经修改，请查阅

2018-07-03 15:18 UTC, blakegao commented on source/_drafts/not-as-many-as-you-think.md
> +不能忽视的是，40 BTC价值几十万美元，以及500万美元有保障，流动投资足以提供一个非常舒适的退休生活。
感谢建议，已经修改，请查阅

2018-07-03 15:18 UTC, blakegao commented on source/_drafts/not-as-many-as-you-think.md
> +当时很容易丢币。 它们的价值不高，所以人们没有花时间保证它们的安全行并支持它们。
感谢建议，已经修改，请查阅

2018-07-04 19:29 UTC, merged

2018-07-04 19:30 UTC, XiaohuaNpc commented
@callmewhy 海，这篇翻译完成了

2018-07-04 19:33 UTC, callmewhy commented
好的，我发布一下